'''

    This program contains a dictionary which stores the sample data i.e titles and abstracts.
    The title is the key and the abstract is the value of the key.

'''

sample_data =
        {
            'Brain inspired cognitive artificial intelligence for knowledge extraction and intelligent instrumentation system':'Artificial intelligence evolves with the development of computers even rely on computational development. The ways and processes of human thinking developed by Psychologists and welcomed by computational experts produce the science of Artificial Intelligence. This continues with the development of cognitive science that encourages the development of Artificial Intelligence to Cognitive Thinking Intelligence, a new pathway to the science of Artificial Intelligence that can emulate human cognitive abilities even if not 100%. Emulation of human cognitive abilities is developed based on the modeling of system interaction with the environment and information fusion, which can be used to conduct Inferencing, so when this occurs repeatedly it will produce knowledge that grows. This process is called Knowledge Growing System which is Brain Inspired Cognitive Artificial Intelligence and can be used for information extraction and when applied to instrumentation system will realize Intelligent Instrumentation System.', # 1
            'Amplifying the Social Intelligence of Teams Through Human Swarming':'Artificial Swarm Intelligence (ASI) is a method for amplifying the collective intelligence of human groups by connecting networked participants into real-time systems modeled after natural swarms and moderated by AI algorithms. ASI has been shown to amplify performance in a wide range of tasks, from forecasting financial markets to prioritizing conflicting objectives. This study explores the ability of ASI systems to amplify the social intelligence of small teams. A set of 61 teams, each of 3 to 6 members, was administered a standard social sensitivity test -“Reading the Mind in the Eyes” or RME. Subjects took the test both as individuals and as ASI systems (i.e. “swarms”). The average individual scored 24 of 35 correct (32% error) on the RME test, while the average ASI swarm scored 30 of 35 correct (15% error). Statistical analysis found that the groups working as ASI swarms had significantly higher social sensitivity than individuals working alone or groups working together by plurality vote (p<;0.001). This suggests that when groups reach decisions as real-time ASI swarms, they make better use of their social intelligence than when working alone or by traditional group vote.', # 2
            'One Quantifiable Security Evaluation Model for Cloud Computing Platform':'Whatever one public cloud, private cloud or a mixed cloud, the users lack of effective security quantifiable evaluation methods to grasp the security situation of its own information infrastructure on the whole. This paper provides a quantifiable security evaluation system for different clouds that can be accessed by consistent API. The evaluation system includes security scanning engine, security recovery engine, security quantifiable evaluation model, visual display module and etc. The security evaluation model composes of a set of evaluation elements corresponding different fields, such as computing, storage, network, maintenance, application security and etc. Each element is assigned a three tuple on vulnerabilities, score and repair method. The system adopts “One vote vetoed” mechanism for one field to count its score and adds up the summary as the total score, and to create one security view. We implement the quantifiable evaluation for different cloud users based on our G-Cloud platform. It shows the dynamic security scanning score for one or multiple clouds with visual graphs and guided users to modify configuration, improve operation and repair vulnerabilities, so as to improve the security of their cloud resources.', # 3
            'Connecting Fog and Cloud Computing':'There is a perfect storm of the use of cloud computing, and the growth of Internet of Things (IoT). IoT is about processing data that comes from devices in some way that is meaningful, and cloud computing is about leveraging data from centralized computing and storage. Growth rates of both can easily become unmanageable. We have some problems to solve. In addition, alternatives are being consider to placing everything in the public cloud because the public cloud, in some cases, no longer makes sense.', # 4
            'Big Data Quality Framework: Pre-Processing Data in Weather Monitoring Application':"Big Data has become an imminent part of all industries and business sectors today. All organizations in any sector like energy, banking, retail, hardware, networking, etc all generate huge quantum of heterogenous data which if mined, processed and analyzed accurately can reveal immensely useful patterns for business heads to apply to generate and grow their businesses. Big Data helps in acquiring, processing and analyzing large amounts of heterogeneous data to derive valuable results. Quality of information is affected by size, speed and format in which data is generated. Hence, Quality of Big Data is of great relevance and importance. We propose addressing various aspects of the raw data to improve its quality in the pre-processing stage, as the raw data may not usable as-is. We are exploring process like Cleansing to fix as much data as feasible, Noise filters to remove bad data, as well sub-processes for Integration and Filtering along with Data Transformation/Normalization. We evaluate and profile the Big Data during acquisition stage, which is adapted to expectations to avoid cost overheads later while also improving and leading to accurate data analysis. Hence, it is imperative to improve Data quality even it is absorbed and utilized in an industry's Big Data system. In this paper, we propose a Pre-Processing Framework to address quality of data in a weather monitoring and forecasting application that also takes into account global warming parameters and raises alerts/notifications to warn users and scientists in advance.", # 5
            'An OWL Ontology for Supporting Semantic Services in Big Data Platforms':"In the last years, there was a growing interest in the use of Big Data models to support advanced data analysis functionalities. Many companies and organizations lack IT expertise and adequate budget to have benefits from them. In order to fill this gap, a model-based approach for Big Data Analytics-as-a-service (MBDAaaS) can be used. The proposed model, composed by declarative, procedural and deployment (sub) models, can be used to select a deployable set of services based on a set of user preferences shaping a Big Data Campaign (BDC). The deployment of a BDC requires that the selection of services has to be carried out on the basis of coherent and non conflictual user preferences. In this paper we propose an OWL ontology in order to solve this issue.", # 6
            'Effective Scheme against 51% Attack on Proof-of-Work Blockchain with History Weighted Information':"Proof-of-Work (PoW) is a popular protocol used in Blockchain systems to resolve double-spending problems. However, if an attacker has access to calculation hash power greater than half of the total hash power, this attacker can create a double-spending attack or 51% attack. The cost of creating a 51% attack is surprisingly low if hash power is abundantly available. That posts a great threat to lots of PoW blockchains. We propose a technique to combine history weighted information of miners with the total calculation difficulty to alleviate the 51% attack problem. Analysis indicates that with the new technique, the cost of a traditional attack is increased by two orders of magnitude."  #7
        }